source:      .
destination: ./_site
includes:    ./_includes
url: "https://www.jeyounson.com"
baseurl: ""
exclude:
  - vendor
  - docs
  - scripts
  - orcid
  - README.md
  - Gemfile
  - Gemfile.lock

collections:
  projects:
    output: true
